ATOMIC_AGENT_SECRET_KEY="your_key"
KEYCLOAK_OAUTH_CLIENT_ID = "your_client_id"
KEYCLOAK_OAUTH_CLIENT_SECRET = "your_client_secret"
ATOMIC_AUTH_HEADER="your_atomic_auth_header"
ATOMIC_AGENT_PRIVATE_KEY="your_atomic_private_key"
ATOMIC_AGENT_SUBJECT="your_agent_subject"
LOCAL_ATOMIC_AGENT_SECRET_KEY="your_local_atomic_secret_key"
LOCAL_ATOMIC_AGENT_PRIVATE_KEY="your_local_private_key"
LOCAL_ATOMIC_AGENT_SUBJECT="your_local_atomic_agent_subject"
LOCAL_ATOMIC_AUTH_HEADER="your_local_atomic_header"